### ISSUE TITLE
Gisborne 2023 acquisition only half-uploaded to S3 bucket?

### ISSUE THREAD

**Issue by bhjolly** [linz/elevation#289]
I've been trying to build a mosaic of the 1m DEM for Gisborne for 2023 using data from s3://nz-elevation but the available files seem to stop at northing 5743680 (NZTM), have all the data been uploaded?

<img width="732" alt="image" src="https://github.com/linz/elevation/assets/15041759/50b9ab94-d974-4300-b8d5-5899bf392af3">

**Comment by amfage** [comment]
Thank you for raising this issue. Datasets may be published in stages. However, these should be labelled `"linz:lifecycle": "ongoing"` in the collection STAC metadata before they are complete, and this dataset was mistakenly labelled `"completed"`. The full dataset has now been uploaded to the ODR so you should have access to all the files. We appreciate you taking the time to raise this.

**Comment by dwsilk** [comment]
Thanks for raising this Ben, do feel free to raise other issues in future if you have any problems. Some time in the next few months our publishing process will change and these DEMs should always be available via s3://nz-elevation just _before_ they go out on the LINZ Data Service.
