### ISSUE TITLE
Hawkes-bay 2023 capture_area.geojson doesn't validate

### ISSUE THREAD

**Issue by BoudewijnBoogaard** [linz/elevation#298]
The geojson for the hawkes-bay-2023 dataset returns an error when running it through the geojson validator. The message from https://geojsonlint.com/ is:

Invalid GeoJSON
Line 2: Polygons and MultiPolygons should follow the right-hand rule

[capture_area.zip](https://github.com/user-attachments/files/15603453/capture_area.zip)

**Comment by dwsilk** [comment]
Thanks @BoudewijnBoogaard 
We'll have a look at it, also aware the Hutt City geojson has a similar problem.

**Comment by dwsilk** [comment]
Anything published since ~August should be fixed but we need to go back through and regenerate all of the older capture areas. Planning to do that in the next 6 months as part of reprocessing the whole archive to take advantage of a variety of improvements we've made recently.
