### ISSUE TITLE
Gisbourne 2023 DSM missing

### ISSUE THREAD

**Issue by duckblaster** [linz/elevation#308]
Just pointing out another missing dataset in the s3 bucket, the DEM was reported previously (#289) but the DSM is also only partially uploaded.

**Comment by dwsilk** [comment]
Thanks for raising this and apologies for the slow response.

The Gisborne 2023 DSM had a processing issue caused by a combination of nodata and data being used within oceans and rivers which is unusual. Just checking whether we can resolve, will report back in a week or so.
